### PR TITLE
Feat/gitpod

### PR DESCRIPTION
**Pull request by amirgon**
Configures lv_micropython to work with [gitpod](https://www.gitpod.io/).

Added "open in gitpod" button on README to open the lv_micropython workspace on gitpod, build the unix port and run advanced_demo.

It supports VNC so the LVGL GUI is displayed to the user in the preview panel.

### CODE REVIEW

**Comment by kisvegabor** [comment]
It look very interesting.  I've just registered to gitpod but didn't know how to proceed. 

Can you give a brief description?

**Comment by amirgon** [comment]
> Can you give a brief description?

It's pretty simple: browse to `https://gitpod.io/#https://github.com/.../...`  

For GUI you need a special container, that's `.gitpod.Dockerfile`  in this PR.
`.gitpod` just points to the docker file, opens the GUI in preview and specify the commands to build the project.

Then you get full VSCode environment where you can develop and run code.
It's nice but a bit slow to start at least with lv_micropython

**Comment by kisvegabor** [comment]
Cool! It's working here too. 

What I can't see is what command tells gitpod (or VS Code) to display the SDL window in VS Code.

It seems we could use it as C editor too, right? The [pricing](https://gitpod.io/plans) seems fair too.

**Comment by amirgon** [comment]
> What I can't see is what command tells gitpod (or VS Code) to display the SDL window in VS Code.

gitpod was designed to display a web page connected to some port, so it could easily host phph or nodejs server that serves web pages.
The trick here is that the web page displays [noVNC](https://novnc.com/info.html) client connected to the machine's display.
This why a special docker image is needed - it opens the VNC connection. Once open, it's enough to ask gitpod to [connect the noVNC port 6080 to the web page preview](https://github.com/amirgon/lv_micropython/blob/91107d176a3a755fb10998ef05ce783ae51c87be/.gitpod#L3-L6).

> It seems we could use it as C editor too, right? The [pricing](https://gitpod.io/plans) seems fair too.

Definitely useful for C. lv_micropython is, in fact, a C project.  
They really have a nice free plan for open source projects.

**Comment by kisvegabor** [comment]
Fantastic!

I haven't found a terminal for REPL or an obvious way to load scripts. Is is possible?

**Comment by amirgon** [comment]
> I haven't found a terminal for REPL or an obvious way to load scripts. Is it possible?

The terminal is there, on the bottom. You can also open multiple terminals if you want.
You can use it as a bash prompt or run Micropython in it.  

image

**Comment by kisvegabor** [comment]
Thanks, I don't know how could I missed it. :smile: 
It's there and working indeed.

BTW, it look good on your screenshot but for me the letters in the Terminal are slightly cropped. Do you have any ideas why it happens?

image

**Pull request merged**
