### PR TITLE
Update lv_bindings

### PR DESCRIPTION
**Pull request by Sh3Rm4n**
To add stdatomic support for micro-python, see https://github.com/lvgl/lvgl/pull/3965. 

Depends on https://github.com/lvgl/lv_binding_micropython/pull/255 to be merged, thus it's a draft for now.

### CODE REVIEW

**Comment by kisvegabor** [comment]
@Sh3Rm4n  https://github.com/lvgl/lvgl/pull/3965 is merged, so could you update this PR?

@amirgon The changes are very minimal, but please take a look at them.

**Comment by Sh3Rm4n** [comment]
This PR is already updated, but it still depends on https://github.com/lvgl/lv_binding_micropython/pull/255 :)

**Comment by amirgon** [comment]
> The changes are very minimal, but please take a look at them

@kisvegabor see the discussion on lvgl/lv_binding_micropython#255, I'm still not convinced it's best to require this include the the generates code. We use the same script for libraries other than LVGL where it may not be needed.

**Comment by kisvegabor** [comment]
What about the latest suggestion of @Sh3Rm4n to just skip `memory_order`?

At worst case we can add `#define LV_USE_ATOMIC 0` to `lv_conf.h` in MicroPython to overwrite the default heuristic which decides whether to use atomic or not.

**Comment by amirgon** [comment]
> What about the latest suggestion of @Sh3Rm4n to just skip `memory_order`?

That's a hack that will prevent generating `memory_order` enum of someone ever wanted to. So I'm not too excited about it.

I didn't have time to look into it, but I still don't understand why this can't be solved by some includes from lvgl.h

**Comment by kisvegabor** [comment]
> That's a hack that will prevent generating memory_order enum if someone ever wanted to. So I'm not too excited about it.

True.

> I didn't have time to look into it, but I still don't understand why this can't be solved by some includes from lvgl.h

I have some ideas, but I think @Sh3Rm4n will explain it better. :slightly_smiling_face:

**Comment by kdschlosser** [comment]
I am not 100% sure of the need for this. The purpose to atomic variables is for multi threading purposes because Micropython doesn't have true multithreading and the threads do not really run concurrently with each. There would be no reason to have any of the variables be atomic. Lock objects aren't needed to threads from altering the same variable. This is because of the GIL and only one thread actually being able to do anything at any given time. Threading in MicroPython is an illusion and not real. I think there might be one MCU with MicroPython that does actually run concurrent threads without the use of the GIL. If someone encountered an issue they would simply need to set MICROPY_PY_THREAD_GIL to true at compile time. Seems like quite a bit for work for only a single use case and that case already has a solution in place for an potential issues that can stem from not having atomic variables.

**Comment by kisvegabor** [comment]
If it's really not applicable to MicroPython we can just force `LV_USE_ATOMIC 0` in `lv_conf.h`. (https://github.com/lvgl/lvgl/pull/3995 needs to be merged)

**Comment by kdschlosser** [comment]
I m seeing this in the micropython bindings and not in LVGL itself is the reason why I am saying that. I thought it was specific to micropython..

Here is a little bit of a blurb on it.
https://forum.micropython.org/viewtopic.php?t=8610&start=10

I believe that CPython is doing away with the GIL and that will allow true threading. But as it sits Python and also MicroPython only process a single thread at a time so it does not offer true parallelism. The threads end up running consecutive to each other and that by definition would mean you would not end up having the same data object being accessed at the same time. That pretty much removes the need for atomic variables. 

That being said... The ESP32 does support concurrent threads and so do other MCUs. So will MicroPython do away with the GIL at some point? More then likely. So it's not a bad idea to add support for it, it's just not something that needs to be done yesterday.

**Comment by Sh3Rm4n** [comment]
I want to clarify some misunderstandings: 

So first in foremost, this PR is needed, so that also micropython is compatible with an lvgl version, which uses atomics. That's why the pycparser update was needed, as only [pycparser v2.21](https://github.com/eliben/pycparser/blob/3cf6bf5eb16f5eadd4a058e41596145c407a79ad/CHANGES#L3) supports atomics. 

> That's a hack that will prevent generating memory_order enum if someone ever wanted to. So I'm not too excited about it.

> I didn't have time to look into it, but I still don't understand why this can't be solved by some includes from lvgl.h

The way pycparser parses the lvgl source, the `memory_order` enum, normally defined in the `stdatomic.h` field is spilled into the preprocessor output, which is used as the bases for `gen_mpy.py` to generate the micropython bindings. 
I've explained this in https://github.com/lvgl/lv_binding_micropython/pull/255#discussion_r1109534803. And with [the commit before the LVGL update](https://github.com/lvgl/lv_binding_micropython/pull/255/commits/1b160ea17aece51ffc4d8949b1b81c65f6179f5a) you could see, that this has nothing to do, with the recent LVGL changes, that lv_bindings does not build anymore, but with the pycparser update. 

Of course the current LVGL atomics approach is not with its [own (1)](https://github.com/lvgl/lvgl/issues/3994#issuecomment-1434162987) [problems (2)](https://github.com/lvgl/lv_micropython/pull/62/files#diff-bf70e57b9f5afd453f578c25adbf304f26ed31520d84989cfb3930ba58ac1c64R353) 

> I am not 100% sure of the need for this. The purpose to atomic variables is for multi threading purposes because Micropython doesn't have true multithreading and the threads do not really run concurrently with each. There would be no reason to have any of the variables be atomic. Lock objects aren't needed to threads from altering the same variable. This is because of the GIL and only one thread actually being able to do anything at any given time. Threading in MicroPython is an illusion and not real. 

Threads in Python (I'm not sure about MicroPython though) are running concurrently, this is not an illusion. The only thing the GIL prevents, is that threads run in **parallel**. But any thread could be preempted at any byte code instruction AFAIK. The GIL exists, so that the interpreter state stays consistent.

I'm not sure, however, if MicroPython threads could preempt another python thread, while it is executed a C-FFI function. If that's not possible, atomics are indeed not that important, otherwise they still are.

I leave this PR open for, but I am tending to revert the recent atomic variables introduction. But this PR (if the lvgl update is excluded) is still needed, if the `pycparser` dependency would ever be udpated.

**Comment by kdschlosser** [comment]
If there are changes to LVGL that is causing issues with the binding and that is what this PR is for fixing then this PR is needed and at the highest priority. I am using the dev branch of LVGL and using the binding and I have not had an issue with compiling at all and it runs fine. I have not come across any issues so far and that is where my confusion on this is coming from. If I was unable to compile and run it would have been more apparent as to the need of this PR.

staying with the most current version of the pycparser would be important I think. I am not the one that makes those decisions tho. 

Now as far as CPython and running threads. The terms parallel and concurrent are interwoven because you cannot have threads run in parallel unless they are running concurrently. The way the verbage is being used has twisted what the meaning of those words are. They both mean at the same time essentially but the way they are being used means otherwise. Python threads do not run at the same time one has to stop before another is able to do what it needs to do. To the user and in code the threads are running at the same time but in reality they are not. The GIL is a lock object just like a thread lock. It serves the same purpose. It stops code from running while one other code is being run. That means the thread is not running concurrently or "at the same time" as another thread.  How the words are being used is a thread is running concurrently because the thread exists. Not because it is actually doing anything. The GIL ensures that while one thread is doing something the rest of them are not. This leads to the word parallel. The term Parallel is being used to describe how the code is being run. Tho concurrently should also be explaining the same thing as well. So while more than one thread is able to exist (concurrent) the code inside of the thread does not run concurrently (parallel). IDK why it has been decided to make it that complicated to understand. The bottom line is that the code in a thread does not execute at the same time as code in another thread and therefor the threads do not run concurrently. They exist at the same time but so do 2 instances of a class. just because 2 of an object exists at the same time does not mean they run at the same time. The same holds true for threads in Python.

I don't know how the backend of CPython is coded in terms of the GIL and when the lock is acquired and released. If data corruption of an object can happen that is because the GIL is being released while a handle to that object is in the middle of being used. In Micropython I do not believe the GIL gets released in the middle of an object being changed. It is acquired at the start and released when the change has been completed. That negates the need for using lock objects in users code to prevent data corruption. Atomic objects work in the same manner so that no corruption can happen in multi threaded applications. This same concept is already in place in MicroPython by default.

It could be me that is misunderstanding how all of this work in Python. If I am not understanding it properly then let me know by all means.

https://towardsdatascience.com/multithreading-multiprocessing-python-180d0975ab29

>The Python Global Interpreter Lock (GIL) prevents threads within the same process to be executed at the same time.

**Comment by kdschlosser** [comment]
I just don't want anyone banging their head against the wall trying to get something to work properly when it may not even be needed and can simply be turned off. Again that is at this point in time it is not needed. It could be a completely different thing a year from now. MicroPython follows CPython. There has been discussion about doing away with the GIL and if that happens the same could happen in MicroPython and then having the atomic variables working in the binding would be needed.

**Comment by Sh3Rm4n** [comment]
Ultimately, the pycparser update is currently not needed anymore to fix any immediate issues regarding atomic support. And, as a better approach should be, that no `stdatomic.h` includes should appear in lvgl header files, because of https://github.com/lvgl/lvgl/issues/3994#issuecomment-1434162987, I don't think the pycparser update is needed for bindings generation in case of atomic usage in the future. 

However, it might be useful to unblock a pycparesr update because of [other bug fixes](https://github.com/eliben/pycparser/blob/c21753191b706bb3c5262454ddcf89ffc92a25d6/CHANGES#L5).

The discussion about threading in python is very off-topic. Especially, because my original motivation was not to introduce atomic support because of the MicroPython environment, but for scenarios of runtimes and operating systems, where the current assumptions about thread-safety do not hold.

But with the introduction of atomic variables, this should not break any other use-cases as well (e.g. MicroPython support), hence this PR. 

>  The terms parallel and concurrent are interwoven because you cannot have threads run in parallel unless they are running concurrently. 

Yeah, parallelism implies concurrency, but concurrency does not necessarily imply parallelism. You don't need parallelism to support concurrency, e.g. (python)-threads. And you still have to use mutexes and such to protect shared state between threads, even if the GIL is in-place. Read this stackoverflow thread for more detailed explanations: https://stackoverflow.com/a/4748838

But this doesn't really matter in the current discussion. Even though the lvgl bindings are safe to use in micropython without dataraces, it does not mean lvgl is protected from data-races in other circumstances.

**Comment by kdschlosser** [comment]
The reasoning behind the changes in the PR is not for the purposes of adding atomic support to the binding. it is to fix an issue due to atomic support in LVGL. At some point it the addition of atomic s into the binding might need to happen tho so it would not necessarily be a bad idea to get the wheels rolling in that direction anyhow. So the logical thing would be to continue with this PR if it only ends up allowing an updated version of pycparser to be used if the new version of pycparser is needed in order to use the atomic variables.

**Comment by amirgon** [comment]
Done in 43ac0377a

**Pull request closed without merging**
