### PR TITLE
WIP: Align to micropython v1.20

### PR DESCRIPTION
**Pull request by amirgon**
TODO: 
- [ ] Fix and test Micropython ports
- [ ] Push LVGL and lv_bindings_micropython submodules to master and point lv_micropython to them

### CODE REVIEW

**Comment by visualecho1** [comment]
I'm hoping you have the time to update the RP2 port for the new pico_w support in MPY 1.20

**Comment by amirgon** [comment]
> I'm hoping you have the time to update the RP2 port for the new pico_w support in MPY 1.20

I would like to, but I don't have an RP2 device to test it.  
After it compiles I'll need some help testing the different ports.

**Comment by visualecho1** [comment]
I am using directions to compile the Raspberry Pi Pico port, and it's working for me:
`MicroPython v1.19.1-685-gb9fae5f2f on 2023-06-13; Raspberry Pi Pico with RP2040`
I also see lgvl on the help("modules") list, and I can "import lgvl as lv". Connecting to REPL with a USB cable, I can run_tests.py, with 16 fails related to assembler, math, and nanoseconds.  Uhmmm... what's the best way to write this up, and/or can I buy you a pico-w?   I'm not having much luck trying to hack this together, would a zip file of the whole text of a clone and compile help?

**Comment by amirgon** [comment]
> Connecting to REPL with a USB cable, I can run_tests.py, with 16 fails related to assembler, math, and nanoseconds.

Did you check this?

https://github.com/lvgl/lv_micropython/blob/808d72d43d0ef0144720a90436ee6fd77be305a4/ports/rp2/README.md?plain=1#L110-L116

Another thing I would check is Garbage Collection. LVGL relies on MP gc so if anything goes wrong there it could cause nasty crashes.  
The easiest thing to do is to `import gc` and call `gc.collect()` while running some LVGL code and see if it crashes due to gc.

How do these failures look like? Do you have a stack trace for them? Can you connect a debugger? Or are these just Python errors?

Regardless of the failures, were you able to run some hello world with a display? The tests are good for logic but don't test the display driver and the event loop. If you are able to run some examples such as the [advanced_demo.py](https://github.com/lvgl/lv_binding_micropython/blob/master/examples/advanced_demo.py), I would be optimistic about the rest.

> what's the best way to write this up, and/or can I buy you a pico-w? I'm not having much luck trying to hack this together, would a zip file of the whole text of a clone and compile help?

Could you open a GitHub issue for that on [lv_binding_micropython](https://github.com/lvgl/lv_binding_micropython/issues)?  
Try to describe the problem, how to reproduce it, the errors you get, stack trace etc.

Currently I have very little time to put into it. For now I won't be able to debug this myself, but if you are willing to try, I'll be happy to discuss, provide feedback etc. Hopefully others would step in and help too.

**Comment by amirgon** [comment]
@embeddedt - I think the stm32 port and js port (renamed to webassembly) need to be fixed for Micropython v1.20
Can you help?

**Comment by sam0910** [comment]
Thank you so much for MP1.20
it works fine with ESP32-SPIRAM, ESP-IDF v4.4.5
New micropython 1.20 features(mip, mpy v6.1) are available :)

I found ./py/mpconfig.h shows,
```
#define MICROPY_VERSION_MAJOR 1
#define MICROPY_VERSION_MINOR 20
#define MICROPY_VERSION_MICRO 0
```
I don't know why REPL shows, 
```MicroPython v1.19.1-1735-gbcaf84455-dirty on 2023-06-18;```

**Comment by embeddedt** [comment]
I've fixed STM32 compilation, however attempting to run `advanced_demo` results in a MemManage fault. It happens when `gc_free` runs so I wonder if this is a missing GC root. Do we have a way of tracking those on the simulator instead of having to debug on the actual platform?

```
#0  0x0809a332 in boardctrl_fatal_error (msg=msg@entry=0x80ede33 "MemManage") at boardctrl.c:49
#1  0x0809ab64 in MemManage_Handler () at stm32_it.c:248
#2  <signal handler called>
#3  0x08020362 in gc_free (ptr=<optimized out>) at ../../py/gc.c:779
#4  0x080209c4 in gc_free (ptr=<optimized out>) at ../../py/gc.c:759
#5  0x08020294 in m_free (ptr=<optimized out>) at ../../py/malloc.c:199
#6  0x08069260 in lv_free (data=<optimized out>) at ../../lib/lv_bindings/lvgl/src/misc/lv_mem.c:106
#7  0x08063460 in lv_img_cache_set_size_builtin (new_entry_cnt=new_entry_cnt@entry=1) at ../../lib/lv_bindings/lvgl/src/draw/lv_img_cache_builtin.c:191
#8  0x08063604 in _lv_img_cache_builtin_init () at ../../lib/lv_bindings/lvgl/src/draw/lv_img_cache_builtin.c:71
#9  0x08055530 in lv_init () at ../../lib/lv_bindings/lvgl/src/core/lv_obj.c:169
#10 0x08041c86 in mp_lv_anim_del_all (mp_n_args=<optimized out>, mp_args=<optimized out>, lv_func_ptr=<optimized out>) at build-STM32F7DISC/lvgl/lv_mpy.c:33359
#11 0x0803962c in mp_execute_bytecode (code_state=code_state@entry=0x2004fc28, inject_exc=inject_exc@entry=0x0) at ../../py/vm.c:1042
#12 0x0803051a in fun_bc_call (self_in=0xc002f640, n_args=<optimized out>, n_kw=0, args=0x0) at ../../py/objfun.c:278
#13 0x0802c0ba in mp_parse_compile_execute (lex=0xc002f630, parse_input_kind=parse_input_kind@entry=MP_PARSE_FILE_INPUT, globals=0xc002f540, locals=<optimized out>) at ../../py/runtime.c:1600
#14 0x08037210 in do_load_from_lexer (context=context@entry=0xc002f520, lex=<optimized out>) at ../../py/builtinimport.c:166
#15 0x0803742e in do_load (module_obj=0xc002f520, file=file@entry=0x2004fd38) at ../../py/builtinimport.c:260
#16 0x08037654 in process_import_at_level (override_main=false, path=0x2004fd38, outer_module_obj=0x0, level_mod_name=4443, full_mod_name=4443) at ../../py/builtinimport.c:460
#17 mp_builtin___import___default (n_args=n_args@entry=5, args=args@entry=0x2004fdf4) at ../../py/builtinimport.c:554
#18 0x0802c1ba in mp_import_name (name=<optimized out>, fromlist=<optimized out>, level=<optimized out>) at ../../py/runtime.c:1508
#19 0x08039542 in mp_execute_bytecode (code_state=code_state@entry=0x2004fea0, inject_exc=inject_exc@entry=0x0) at ../../py/vm.c:1233
--Type <RET> for more, q to quit, c to continue without paging--c
#20 0x0803051a in fun_bc_call (self_in=0xc002f510, n_args=<optimized out>, n_kw=0, args=0x0) at ../../py/objfun.c:278
#21 0x0808f80a in parse_compile_execute (source=source@entry=0x2004ff80, input_kind=<optimized out>, exec_flags=exec_flags@entry=22) at ../../shared/runtime/pyexec.c:123
#22 0x0808fbd6 in pyexec_friendly_repl () at ../../shared/runtime/pyexec.c:675
#23 0x0809a960 in stm32_main (reset_mode=<optimized out>) at main.c:617
```

**Comment by amirgon** [comment]
> Thank you so much for MP1.20
> it works fine with ESP32-SPIRAM, ESP-IDF v4.4.5
> New micropython 1.20 features(mip, mpy v6.1) are available :)

@sam0910 - Thank you very much for testing this branch on ESP32!

> I don't know why REPL shows,
> `MicroPython v1.19.1-1735-gbcaf84455-dirty on 2023-06-18;`

Probably I need to push the v1.20.0 tag to GitHub.

---

@embeddedt - Thanks for the help!  

I believe the GC problem is specific to stm32 because I tested the unix port, and GC works fine there.  
My guess is that it's related to `MP_REGISTER_ROOT_POINTER` (see [this commit](https://github.com/lvgl/lv_binding_micropython/compare/880b2c30dd68674f6887773a41787cfd7eb68685...a9d3531ec9c33c16e3f8989e100ac18451faf5e8#diff-29002e3002350475d2fc184ac4b921a25d9665bf1ceb8894a1ad25f2d5af5510)) and to the stm32 Makefile.  

In Micropython v1.20, some Python script scans the sources and looks for `MP_REGISTER_ROOT_POINTER` in the sources. This macro is defined to nothing in C, but used to hint the build system to add a root pointer.  

Maybe the source (driver/stm32/STM32F7DISC/modrk043fn48h.c) is not added to the correct Makefile variable. Perhaps we can add it to `SRC_EXTMOD_C` instead, [like done for `lv_mpy.c`](https://github.com/lvgl/lv_micropython/blob/4766e9457b66e27f935da13ceb68667fceaa1e16/extmod/extmod.mk#L394).   
`lv_mpy.c` also defines `MP_REGISTER_ROOT_POINTER` and it works well there. On the other hand, modrk043fn48h is not exactly an external module (it's specific to stm32) so I'm not sure `SRC_EXTMOD_C` is the right parameter here.

**Comment by embeddedt** [comment]
False alarm. My LVGL submodule was somehow out of date and therefore didn't have https://github.com/lvgl/lvgl/pull/4269, which meant `lvgl_root_pointers` was null. STM32 appears to be working fine now.

**Comment by embeddedt** [comment]
JS will definitely have a merge conflict but it is on a separate branch so I can update it later, shouldn't block any other development.

**Comment by amirgon** [comment]
> JS will definitely have a merge conflict but it is on a separate branch so I can update it later, shouldn't block any other development.

Right. https://github.com/lvgl/lv_micropython/actions/runs/5305529951/jobs/9602554249

I suspect it's more than a simple merge problem. The js port was renamed "webassembly" and I'm not sure what other changes were done.  
Do you use root pointers anywhere in the js port?

**Comment by embeddedt** [comment]
JS port should be updated now. (I guess it should now be called the WASM port?)

The real URL is now https://sim.lvgl.io/v9.0/micropython/ports/webassembly/index.html but I implemented a symlink so https://sim.lvgl.io/v9.0/micropython/ports/javascript/index.html still works too.

Let me know if there are any issues.

**Comment by amirgon** [comment]
Thank you @embeddedt !

**Pull request merged**
