### PR TITLE
Zephyr OS port: invalid merge of CMakeLists.txt

### PR DESCRIPTION
**Pull request by svetelna**
Hello,

would it be please possible to update/remerge the CMakeLists.txt in Zephyr port, which have been merged incorrectly?

This PR contains adaptation of Zephyr port's CMakeLists.txt to a state as it is in the main Micropython repository.

### CODE REVIEW

**Comment by embeddedt** [comment]
That'd be my fault, as I was the last person to merge upstream. Sorry! We don't have CI on the Zephyr port and I don't have the tooling installed to test it locally.

**Comment by svetelna** [comment]
@embeddedt Thanks for merging. I have noticed it, because I have just started working on the Zephyr port CI test. I hope I will manage to finish it soon :).

**Comment by embeddedt** [comment]
No problem; that's great to hear!

**Comment by svetelna** [comment]
Hello,
I have a problem with building zephyr port on lv_micropython on current master branch.
However, current master branch of upstream micropython is buildable for zephyr port without problem.
Unfortunately I got into the point where I do not now how to effectively proceed with debugging.

The things which I already discovered are as follows:
- zephyr port in lv_micropython master is unbuildable, however upstream works OK.
- zephyr port is currently being built with use of cmake.
- source codes of the zephyr port in lv_micropython are not in same state as in micropython, hovewer the CmakeFiles are the same.
- build of zephyr port in lv_micropython in step of generating the `genhdr/qstrdefs.preprocessed.h` fails and the file, which is generated in this step is not correct. The error looks like this:
```
/home/xxx/zephyrproject/micropython/ports/zephyr/../../py/qstr.h:44:14: fatal error: genhdr/qstrdefs.generated.h: No such file or directory
   44 |     #include "genhdr/qstrdefs.generated.h"
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[200/395] Generating genhdr/qstrdefs.generated.h
FAILED: genhdr/qstrdefs.generated.h /tmp/build/genhdr/qstrdefs.generated.h 
cd /tmp/build && /usr/bin/python3.9 /home/xxx/zephyrproject/micropython/ports/zephyr/../../py/makeqstrdata.py /tmp/build/genhdr/qstrdefs.preprocessed.h > /tmp/build/genhdr/qstrdefs.generated.h
ERROR: Empty preprocessor output - check for errors above
ninja: build stopped: subcommand failed.
```
- when the `qstrdefs.generated.h` is created manually during the configuration process with `touch` command the error is not present, but still the generated `qstrdefs.preprocessed.h` is invalid - cut in the middle of the file and the `qstrdefs.generated.h` step fails.
- when the command generating the `genhdr/qstrdefs.preprocessed.h` is run manually in commandline, the  `genhdr/qstrdefs.preprocessed.h` file is generated correctly, and build proceeds (to other errors).


This problem is not related to adding LVGL binding to the Zephyr port and is not caused by it (in my opinion).

Do you please have any advice for proceeding?

**Comment by amirgon** [comment]
> * when the `qstrdefs.generated.h` is created manually during the configuration process with `touch` command the error is not present, but still the generated `qstrdefs.preprocessed.h` is invalid - cut in the middle of the file and the `qstrdefs.generated.h` step fails.
> * when the command generating the `genhdr/qstrdefs.preprocessed.h` is run manually in commandline, the  `genhdr/qstrdefs.preprocessed.h` file is generated correctly, and build proceeds (to other errors).

Maybe this is something related to build order and build dependecies?

If you run the command from command line and `genhdr/qstrdefs.preprocessed.h` file is generated correctly, but when you run the **exact** same command from cmake it fails, it's a hint that it might be related to **when** the command runs. If it runs too soon when one of its dependencies is not ready yet (or being created in parallel) it might fail.

I would recommend trying to understand what  `genhdr/qstrdefs.preprocessed.h` depends on and try to add the missing depedencies. I'm actually not sure how and where it is created in the CMake flow.

Actually we just identified today a CMake dependencies problem (see https://github.com/lvgl/lvgl/pull/2444) but I don't think it's related to the problem you are seeing. You can try to apply that fix anyway. 

My understanding of CMake flow of the esp-idf + micropython (and of CMake in general) is very superficial so I may be totally wrong here. Please let us know if you reach any conclusions!

**Comment by svetelna** [comment]
Thank you for your answer!

>Maybe this is something related to build order and build dependecies?

>If you run the command from command line and genhdr/qstrdefs.preprocessed.h file is generated correctly, but when you run the exact same command from cmake it fails, it's a hint that it might be related to when the command runs. If it runs too soon when one of its dependencies is not ready yet (or being created in parallel) it might fail.

Interesting is, that I did not find any relevant differences between any CMake files in upstream micropython and in lv_micropython.

>Actually we just identified today a CMake dependencies problem (see lvgl/lvgl#2444) but I don't think it's related to the problem you are seeing. You can try to apply that fix anyway.

I too think, that this problem is probably not related to LVGL code or build, since the build fails on building Micropython itself.

I can try to debug some more..

**Pull request merged**
