### PR TITLE
Update LVGL to v9

### PR DESCRIPTION
**Pull request by PGNetHun**
Update `master` branch to LVGL v9: https://github.com/lvgl/lvgl/commit/09cb87cdc6a0168a98bc0a3182a8439b13249ead

### CODE REVIEW

**Comment by PGNetHun** [comment]
@kisvegabor 
Can you please approve PR?

**Comment by PGNetHun** [comment]
**Reminder:**
After PR is merged to `master`, do not forget to update LVGL MicroPython CI build:
https://github.com/lvgl/lvgl/blob/master/.github/workflows/build_micropython.yml#L26

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
I don't know if you would you like to squash or rebase the PRs, so leave merging to you :slightly_smiling_face:

**Comment by kisvegabor** [comment]
https://github.com/lvgl/lvgl/pull/5460 will update the CI.

**Comment by PGNetHun** [comment]
> I don't know if you would you like to squash or rebase the PRs, so leave merging to you 🙂

Squash merge. Is that OK for you?

**Comment by PGNetHun** [comment]
But there is another problem: 
Although I have write access to repo, but I'm not authorized to merge PR:
image

**Comment by kisvegabor** [comment]
Does merging work now?

**Comment by PGNetHun** [comment]
> I've updated some settings. Does merging work now?

Yes, from my forked repo to `feat/multi-instace` branch PR merging worked: https://github.com/lvgl/lv_micropython/pull/68
But merging from `feat/multi-instance` to `master` is not enabled for me, 'cause I'm not authorized.

**Comment by kisvegabor** [comment]
Now I removed all rules from the master branch. Let's see if it works now. If not, maybe it's just not applied for old PRs.

**Comment by PGNetHun** [comment]
@kisvegabor 
It works now, PR is merged to master

**Comment by kisvegabor** [comment]
Cool!

**Pull request merged**
