### PR TITLE
Define MICROPY_INCLUDED_PY_MPSTATE_H defore include lv_gc.h

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
to avoid the recursived inclusion

### CODE REVIEW

**Comment by amirgon** [comment]
Hi @xiaoxiang781216, thank you for your contribution!

You only applied the change to the unix port, what about other supported ports? (ESP32, STM32, Javascript)

**Comment by xiaoxiang781216** [comment]
@amirgon you are right, I forgot these ports, please review the update which include unix, windows, esp32 and stm32, but I can't find javascript.

**Comment by embeddedt** [comment]
JavaScript is in its own branch (`lvgl_javascript`). If you want, this change can be merged and I'll apply the change to the JS port myself.

**Comment by xiaoxiang781216** [comment]
> JavaScript is in its own branch (`lvgl_javascript`). If you want, this change can be merged and I'll apply the change to the JS port myself.

@embeddedt see here: https://github.com/lvgl/lv_micropython/pull/24
which update javascript port too.

**Pull request merged**
