### PR TITLE
Feat/gitpod - prebuilds

### PR DESCRIPTION
**Pull request by amirgon**
Enable [gitpod prebuilds](https://www.gitpod.io/docs/prebuilds) .  

Also, update unix port specific submodules assuming that sometime it would be possible to prevent gitpod from updating all submodules. ([related forum post](https://community.gitpod.io/t/gitpod-so-slow-to-start/4512/6))

### CODE REVIEW

**Comment by embeddedt** [comment]
What would happen if we ran `git submodule update --init --recursive` in the prebuild step? Would that shift all the submodule work out of the loading stage? I'm hoping that Gitpod's re-run of that command on already initialized submodules would be much faster.

**Comment by amirgon** [comment]
> What would happen if we ran `git submodule update --init --recursive` in the prebuild step?

Actually - currently all submodules are updated during prebuild step.
And the make also runs during prebuild step.
So we get a ready-to-run Micropython environment right away when it starts.

image

The time that we wait now for the workspace to start is only the time it takes to "Pull container image" + the time for "Loading the prebuild data".

Tried now and this was 1 or 2 minutes. Still long but better than 5 minutes.

Could you see how much time it takes you to run this? https://gitpod.io/#https://github.com/lvgl/lv_micropython

**Comment by embeddedt** [comment]
I'm currently stuck on the "Allocating resources..." step.

**Comment by embeddedt** [comment]
It took about 6 minutes to start in total.

**Comment by amirgon** [comment]
> It took about 6 minutes to start in total.

They scale poorly.  
I was probably lucky to start in 2 minutes.  
I hope they fix this soon. From the forum discussion it looks like they are aware of the problem.

**Pull request merged**
