### PR TITLE
ports/esp32/boards/M5CORE2: add support for M5Stack Core2

### PR DESCRIPTION
**Pull request by ropg**
This PR also fast-forwards lv_bindings a few commits to get access to the recently added ft6x36 and axp192 drivers.

This was in a previous PR [here](https://github.com/lvgl/lv_micropython/pull/27), which was closed for reasons of relative git-incompetency on my part.

### CODE REVIEW

**Comment by ropg** [comment]
For the next step after this: the ft6x36 driver and the minimal demo driver on lv_binding_micropython as well as the main.py that is written to flash by inisetup.py over here on lv_micropython all need to be lightly modified for v8. How do I get the drivers there: do I merge these changes to dev-8.0 ? Or do you want to do that?

**Comment by amirgon** [comment]
> all need to be lightly modified for v8. How do I get the drivers there: do I merge these changes to dev-8.0 ? Or do you want to do that?

I think you can merge your files into dev-v8 with the required changes.   

LVGL v8 is about to be released, but it would take me a little more time to release Micropython+LVGL v8 (still need to fix examples, drivers, etc.) so it's good to have your changes already merged, particularly since I can't test them on HW.

**Comment by amirgon** [comment]
Merged!

Thank you.

**Comment by ropg** [comment]
I'll do that tomorrow, and then all my things are tested on 8.0.

I spent some time today playing with the javascript simulator. That's fun... I have some ideas that I'd like to discuss at some point. The forum the right place for that?

**Comment by amirgon** [comment]
> I spent some time today playing with the javascript simulator. That's fun... I have some ideas that I'd like to discuss at some point. The forum the right place for that?

The forum is the place for questions, general discussions, showing off your projects etc.  
GitHub issues are the place for reporting bugs, but also for some technical discussions.

**Comment by embeddedt** [comment]
There is also an open issue for the JavaScript simulator development here: https://github.com/lvgl/lvgl/issues/1320

**Pull request merged**
