### PR TITLE
Merge MicroPython master

### PR DESCRIPTION
**Pull request by embeddedt**
The motivation here is that I wanted to start tinkering with the newer JS port now without having merge conflicts in `dev-8.0` later.

Tested on STM32 and confirmed that advanced_demo still works. As you know I can't test the Unix port (still get that crash).

Fixes lvgl/lv_binding_micropython#160

### CODE REVIEW

**Comment by amirgon** [comment]
- Did you need to fix any conflicts?
- Some js tests fail. Is this expected?

> As you know I can't test the Unix port (still get that crash).

Would you have time to debug this further?
Maybe it would work with the [new event loop](https://github.com/lvgl/lv_binding_micropython/issues/154)?

**Comment by embeddedt** [comment]
> Did you need to fix any conflicts?

Yes. I think the only major one was in `modffi.c` (change from `printf` to `mp_printf`).

> Some js tests fail. Is this expected?

There is an issue with the new Makefile from upstream; it seems to be preprocessing header files in C++ mode instead of C mode (if I'm understanding the warning correctly). This causes `gen_mpy.py` to fail.

On our simulator branch I worked around this by reusing the existing preprocessor line which [forces C mode](https://github.com/lvgl/lv_micropython/blob/5cc22714588cb75ccf48ba10e491619a1307fec8/ports/javascript/Makefile#L37-L38). I don't know if this is the right fix though, as it would prevent C++ from working properly.

> Would you have time to debug this further?

I have not had a chance to investigate the root cause of that crash. It would probably involve needing to create a small, independent repro case in C first, to ease debugging.

I can try it with the new event loop though.

**Comment by embeddedt** [comment]
> I still see some differences from micropython upstream in your merge. Any idea why?

I probably didn't match the spacing perfectly with upstream, as I didn't use `git checkout --theirs` when doing the merge, since I wasn't sure whether you had made other changes to `modffi.c` here which we wanted to keep.

I can redo the merge and be more aggressive about checking out the upstream versions of files.

> Any idea why `lib/mbedtls` is different than micropython upstream?

I didn't touch that submodule. Maybe Git uses whatever version I had checked out in the repository at the time?

> Could you remind me why this [commenting out ssl and mbedtls in mpconfigboard.mk] was needed?

We ran out of flash on the STM32 port. I had to disable these libraries so LVGL would fit.

> This can be done, for example, by adding a new LV_CPP makefile variable that is usually set to CPP but in certain cases is set to some other command that sets C mode. (and use LV_CPP [here](https://github.com/lvgl/lv_micropython/blob/389e952490bcd776fb9cda0f7045e4d0a43c94c7/py/py.mk#L46) instead of CPP)

If we know that `pycparser` (and thus `gen_mpy.py`) can never handle C++ syntax, what do you think about adding `-x c` directly to the invocation of `CPP` in `py.mk`? Then the additional `LV_CPP` variable is not needed.

**Comment by amirgon** [comment]
> If we know that `pycparser` (and thus `gen_mpy.py`) can never handle C++ syntax, what do you think about adding `-x c` directly to the invocation of `CPP` in `py.mk`? Then the additional `LV_CPP` variable is not needed.

That's a good idea.

I'm planning to sync to this PR locally and test it with the unix and ESP32 ports, when I have some time.

**Comment by embeddedt** [comment]
All checks now pass on this branch.

**Comment by amirgon** [comment]
I've checked it on the unix and esp32 ports.

Merged.

**Pull request merged**
