### PR TITLE
Reduce size of mpy flash filesystem to make room for lvgl

### PR DESCRIPTION
**Pull request by campbellsan**
Please see discussion at:

https://forum.lvgl.io/t/lv-micropython-crashing-on-rp2040-pico-board/8282

Note this change is on a branch to allow it to be promoted independently of upcoming driver contributions.

### CODE REVIEW

**Comment by embeddedt** [comment]
Unless I've missed something, we/upstream can prevent this from happening in the future by adding a check at startup that `MICROPY_HW_FLASH_STORAGE_BASE` is greater than `__data_end__`. (It would be more ideal to do this in the linker for compile-time safety as well, but it doesn't appear that Micropython wired their linker scripts to be able to use preprocessor directives.

**Comment by campbellsan** [comment]
@embeddedt 
Yep, a feature like that would have made diagnosis quick and easy. I don't see MICROPY_HW_FLASH_STORAGE_BASE or any of the associated symbols in the elf map, so I think you are right, they're not available to the linker.

In my build, __data_end__ is in SRAM. Since this issue is with overwriting flash, I was thinking __binary_info_end or more likely __flash_binary_end would be the linker symbol to check, at least in the rp2 port. In my build, the latter symbol is 0x100edfcc, leaving a headroom of about 73kB with the fix in place.

I think regardless of your proposed improvement, this change is still recommended to allow rp2 users to have success with lv_micropython out of the box.

**Comment by amirgon** [comment]
@campbellsan Thank you for this contribution!

Could you add a few words about this on the [rp2 section of the README](https://github.com/lvgl/lv_micropython#raspberry-pi-pico-port)?  It could be useful for a user who uses some rp2 board other than PICO, or if LVGL code ever becomes larger, or in case the user has their own objects that consume program size.

I absolutely agree with @embeddedt that it's best to give some error if this problem happens (on any rp2 board, not just PICO). So if you could also add that check (even at runtime, if it's harder to do on compile time) it would be great!

**Comment by campbellsan** [comment]
@amirgon 
I agree that producing an error is desirable. However, isn't this more generic than even rp2 boards? I'm sure many micropython host boards share limited flash between the mpy firmware and the filesystem.

If this is true, then the check should be added upstream, no? Also, the check would need to be implemented differently depending on the processor, board and build system, right?

**Comment by amirgon** [comment]
> However, isn't this more generic than even rp2 boards? I'm sure many micropython host boards share limited flash between the mpy firmware and the filesystem.

This check would be different for every architecture. On ESP32, for example, build simply fails if program has no more room. Possibly rp2 is unique by not providing some protection mechanism against this.

> If this is true, then the check should be added upstream, no?

Sure - it would be very desirable to have it on Micropython upstream.  
My experience is that it might take very long to push something upstream (I have a [certain PR there](https://github.com/micropython/micropython/pull/6896) that is waiting for over a year now!) so I would be happy to push this now to lv_micropython and remove this when it's merged to upstream, if that ever happens.

> Also, the check would need to be implemented differently depending on the processor, board and build system, right?

Today we support on lv_micropython only the following ports: unix (and windows?), ESP32, STM32 and RP2.
This issue is irrelevant for unix/windows and already handled on ESP32. So we are left with RP2 and STM32.
@embeddedt do you know if STM32 port handles this problem?

For now, I'm perfectly ok with fixing this on rp2 only.

**Comment by campbellsan** [comment]
@amirgon I have added some troubleshooting advice as requested.

Can you give me some guidance as to where a startup check should be implemented? I think I know what check is needed, just not where is the best place to put it.

**Comment by amirgon** [comment]
> Can you give me some guidance as to where a startup check should be implemented?

If you check this on runtime, why not simply put if on [main](https://github.com/lvgl/lv_micropython/blob/a0d5004bfc97e9f9ddd4d00dae873481779a6150/ports/rp2/main.c#L64)?

**Comment by campbellsan** [comment]
Sure, but where in main?

Too early and the USB won't be running, so no error message will be possible. Too late and the firmware is corrupt.

**Comment by embeddedt** [comment]
> do you know if STM32 port handles this problem?

I believe it fails at compile time. I recall size-related linker errors. but I'd have to check that those were for overrunning the storage space and not overrunning the whole flash.

**Comment by campbellsan** [comment]
@embeddedt Yes, a link time check makes sense.

I've been able to implement a runtime check, but I can't get it to output to the shell, except in the case the user uses Ctrl-D, and not at all if I use an assert to halt.

By this time, the corruption has already happened, so if it has trashed enough of the firmware it may not even be able to show a REPL. I think a link time check is the only reliable option.

**Comment by campbellsan** [comment]
Ok, so
    `ASSERT(MICROPY_PICO_HW_FLASH_STORAGE_BASE >= __flash_binary_end, "filesystem overlaps firmware")`

added to memmap_mp.ld catches the issue, but you have to compute the value of that symbol ofc. You need to pass something like:

 `-Xlinker --defsym -Xlinker MICROPY_PICO_HW_FLASH_STORAGE_BASE=0x10000000+0x200000-0x12c000`

to the link step, but those three values (XIP_BASE, PICO_FLASH_SIZE_BYTES and MICROPY_HW_FLASH_STORAGE_BYTES) need to come from the #defines which as we have noted are not available at link time. It would be easier if those values were specified at the CMake level and used to define the #define values at compile time.

IMO, this has jumped in scope beyond the original fix remit.

**Comment by embeddedt** [comment]
I looked into whether it'd be possible to preprocess the linker script (which would allow including a header containing these values), but it seems that the linker is mostly controlled by the Pico SDK, not the CMake file here, so that wouldn't be very feasible without a lot of extra logic. Your original fix plus the note you added is probably the best solution for now.

**Review by embeddedt — APPROVED** [review]

**Comment by amirgon** [comment]
> IMO, this has jumped in scope beyond the original fix remit.

Ok, got it.

Merged! Thanks for this contribution!

**Pull request merged**
