### PR TITLE
add CI build for rp2 port (tentative)

### PR DESCRIPTION
**Pull request by eudoxos**
As requested here: https://github.com/lvgl/lv_micropython/pull/42#issuecomment-915564215 modeled after the stm32 port. I don't know how to test it.

### CODE REVIEW

**Comment by amirgon** [comment]
It looks good: https://github.com/lvgl/lv_micropython/pull/44/checks?check_run_id=3552919447

@eudoxos - Why is it "tentative"?
@embeddedt - Any comments about this PR?

**Comment by eudoxos** [comment]
> @eudoxos - Why is it "tentative"?

Because I could not test it before doing the PR (the CI only runs on master). Good that it worked! :)

**Review by embeddedt — APPROVED** [review]

**Comment by embeddedt** [comment]
Thanks! I have merged it with one tweak to speed up submodule cloning. It's not your fault; I needed to make the same change to STM32 as some point as well.

**Comment by amirgon** [comment]
@eudoxos I've added a small bugfix to `mkrules.cmake` and it seems to fail only on the rp2 port (thanks to the CI!).  

For some reason it complains that "[target_compile_options called with incorrect number of arguments](https://github.com/lvgl/lv_micropython/runs/3581329647#step:7:20)" for [this line](https://github.com/lvgl/lv_binding_micropython/blob/9883cdca22f1d3cd3e7895641c57a01f003af8d9/mkrules.cmake#L38):

```cmake
  target_compile_options(${COMPONENT_LIB} PRIVATE ${LV_COMPILE_OPTIONS})
```

Any idea why? Could it be related to the fact that it's defined as an "Interface" library only on rp2?

**Comment by eudoxos** [comment]
> Any idea why? Could it be related to the fact that it's defined as an "Interface" library only on rp2?

`COMPONENT_LIB` is [target declared by ESP-IDF](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#preset-component-variables) thus `${COMPONENT_LIB}` will expand to nothing on other platforms, hence "incorrect number of arguments to `target_compile_options`. That line should be guarded by `if(PLATFORM_ESP)` as other esp-specific stuff. I wonder how come it did not fail before...

**Comment by amirgon** [comment]
> I wonder how come it did not fail before...

Because I just added it as part of a bugfix.

I've tried using `add_compile_options` but that didn't work for ESP32.  
I can use `target_compile_options` for ESP32 and `add_compile_options` for RP2, but I wonder whether `add_compile_options` really has any effect on the RP2 port or just being ignored in all platforms.  
If it is being ignored then the build would still succeed but lodepng would be built the wrong way (see [this forum post](https://forum.lvgl.io/t/lodepng-error-memory-allocation-failed-esp32/6777))

Could you confirm that `add_compile_options` really applies the flags as we expect on RP2?

**Comment by eudoxos** [comment]
`add_compile_options` should be added to compile options globally for all subsequently defined targets, so it should work for RP2 as well; perhaps it did not work for ESP32 as the `${COMPONENT_LIB}` was declared before (somewhere inside the IDF cmake files)..

The proper way, though is `target_compile_options`, as it is target-bound and automatically picked up by all targets which link against it. (They call it "modern cmake" vs. old cmake, think global variables vs. modern approaches).

Perhaps the best would be to say `target_compile_options(lvgl_interface INTERFACE ${LV_COMPILE_OPTIONS})`, that should work for RP2.

My suggestion would be to add something like

```c
#ifndef LODEPNG_NO_COMPILE_ALLOCATORS
   #error LodePNG must be compiled with LODEPNG_NO_COMPILE_ALLOCATORS, which should be passed by the build system, but was not.
#endif 
```
inside the bindings C source so that failing to pass the correct definition at compile-time is detected for all ports.

**Comment by amirgon** [comment]
Thanks for the suggestions!
Added on https://github.com/lvgl/lv_binding_micropython/commit/8648a294a36639fd4790733aff28592623992e46

**Comment by amirgon** [comment]
@eudoxos - This didn't quite work for the rp2:  
https://github.com/lvgl/lv_micropython/runs/3591918923?check_suite_focus=true

**Comment by eudoxos** [comment]
OIC... the target `lvgl_interface` was not delared yet.. Maybe changing the order in `bindings.cmake` would help, like this. I am sorry, traveling these days and cannot check the build for you. Perhaps in the evening or tomorrow. 
```cmake
include(${CMAKE_CURRENT_LIST_DIR}/mkrules.cmake)
include(${LVGL_DIR}/CMakeLists.txt) # declares lvgl_interface target
all_lv_bindings() # this uses the lvgl_interface target (and sets PNG options as well)
# the rest of the file here
```

**Pull request merged**
